database:
  user: postgres
  password: 2020
  host: host.internal
  port: 5432
  dbname: auth
  sslmode: disable

service:
  host: 0.0.0.0
  port: 9000

billing:
  host: localhost
  port: 8080

currency:
  host: localhost
  port: 8000